###
GET http://localhost:3001/api/blogs

###
POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IjE2Z3VpdGFyIiwiaWQiOjEsImlhdCI6MTY1MzkyODUzOX0.zNEZqRxhe_dDipjMdkrQ9B8dKrlmLDLSIsv65HVrcBk

{
    "author": "author 3",
    "url": "url 3",
    "title": "title 3"
}

###
PUT  http://localhost:3001/api/blogs/1
Content-Type: application/json

{
    "likes": 10
}

###
DELETE  http://localhost:3001/api/blogs/10
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InR6dmlrYTEyQGdtYWlsLmNvbSIsImlkIjoyLCJpYXQiOjE2NTM5Mjg5MjF9.wr8qh5RemZjPG1qTniLjCedPxD4wZO4EeaNZmh9z9Qs